version: "3.1"

services:
  db:
    container_name: database
    image: postgres:14
    environment:
      PG_PASSWORD: $PG_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python main.py
    restart: always
    volumes:
      - .:/src
    networks:
      - botnet
    depends_on:
      - db

networks:
  botnet:
    driver: bridge


